### ISSUE TITLE
getting this error

### ISSUE THREAD

**Issue by sudheerbez** [abhi5658/search-youtube#3]
E/memtrack: Couldn't load memtrack module
2019-07-11 22:04:14.029 26229-26229/cf.jrntr.app E/RecyclerView: No adapter attached; skipping layout
2019-07-11 22:04:14.370 26229-26229/cf.jrntr.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cf.jrntr.app, PID: 26229
    java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
        at cf.jrntr.app.YoutubeAdapter.getItemCount(YoutubeAdapter.java:172)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3834)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3639)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)

**Comment by abhi5658** [comment]
Your youtube search would not have returned any results may be due to incorrect api call, query or bad network request which could  have led to this.
